#!/usr/bin/env python3
"""Fetch lofi-relevant radio stations from radiopotok.ru and emit a YAML preset.

Re-run anytime to regenerate configs/radiopotok.yaml from upstream.
"""

import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

CATEGORIES = ["chillout", "jazz", "classical", "trance"]
BASE_URL = "https://radiopotok.ru"
USER_AGENT = "Mozilla/5.0 (compatible; lofi-player-preset/1.0)"
OUTPUT = Path(__file__).resolve().parent.parent / "configs" / "radiopotok.yaml"

STATION_RE = re.compile(r"STATIONS\[\d+\]\s*=\s*(\{.*?\});", re.DOTALL)


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8", errors="replace")


YOUTUBE_ID_RE = re.compile(r"^[A-Za-z0-9_-]{11}$")


def pick_stream(stream_list: list[dict]) -> tuple[str, str] | None:
    """Pick best (url, kind). Prefer http(s) mp3 > aac > other > m3u8.
    Falls back to YouTube ID -> watch URL when nothing else is usable.
    Returns None if no usable entry exists.
    """
    if not stream_list:
        return None
    by_kind: dict[str, list[str]] = {"mp3": [], "aac": [], "m3u8": [], "other": []}
    youtube_ids: list[str] = []
    for s in stream_list:
        raw = (s.get("file") or "").strip()
        if not raw:
            continue
        if raw.startswith(("http://", "https://")):
            low = raw.lower()
            if ".mp3" in low:
                by_kind["mp3"].append(raw)
            elif ".aac" in low or ".aacp" in low:
                by_kind["aac"].append(raw)
            elif ".m3u8" in low:
                by_kind["m3u8"].append(raw)
            else:
                by_kind["other"].append(raw)
        elif YOUTUBE_ID_RE.match(raw):
            youtube_ids.append(raw)
    for kind in ("mp3", "aac", "other", "m3u8"):
        if by_kind[kind]:
            return (by_kind[kind][0], "stream")
    if youtube_ids:
        return (f"https://www.youtube.com/watch?v={youtube_ids[0]}", "youtube")
    return None


def parse_category(html: str) -> list[tuple[str, str, str]]:
    out = []
    for m in STATION_RE.finditer(html):
        try:
            station = json.loads(m.group(1))
        except json.JSONDecodeError:
            continue
        name = (station.get("name") or "").strip()
        stream_raw = station.get("stream") or ""
        if not name or not stream_raw:
            continue
        try:
            streams = json.loads(stream_raw)
        except json.JSONDecodeError:
            continue
        picked = pick_stream(streams)
        if picked:
            url, kind = picked
            out.append((name, url, kind))
    return out


def yaml_escape(s: str) -> str:
    if re.search(r"[:#\[\]{}&*!|>'\"%@`,]", s) or s.startswith(("- ", "? ", " ")) or s.endswith(" "):
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return s


def main() -> int:
    seen_urls: set[str] = set()
    seen_names: set[str] = set()
    stations: list[tuple[str, str, str]] = []

    for cat in CATEGORIES:
        url = f"{BASE_URL}/{cat}"
        print(f"fetching {url}...", file=sys.stderr)
        try:
            html = fetch(url)
        except (urllib.error.URLError, TimeoutError) as e:
            print(f"  failed: {e}", file=sys.stderr)
            continue
        cat_stations = parse_category(html)
        added = 0
        for name, stream, kind in cat_stations:
            if stream in seen_urls or name in seen_names:
                continue
            seen_urls.add(stream)
            seen_names.add(name)
            stations.append((name, stream, kind))
            added += 1
        print(f"  parsed {len(cat_stations)} cards, added {added} new", file=sys.stderr)

    stations.sort(key=lambda x: x[0].lower())

    yt_count = sum(1 for _, _, k in stations if k == "youtube")
    lines = [
        "# Generated by scripts/fetch-radiopotok.py from https://radiopotok.ru",
        f"# Categories: {', '.join(CATEGORIES)}",
        f"# {len(stations)} stations ({yt_count} via YouTube, requires yt-dlp on PATH)",
        "# To use: copy entries below into your ~/.config/lofi-player/config.yaml",
        "stations:",
    ]
    for name, stream, kind in stations:
        lines.append(f"  - name: {yaml_escape(name)}")
        lines.append(f"    url: {stream}")
        if kind == "youtube":
            lines.append(f"    kind: {kind}")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nwrote {len(stations)} stations to {OUTPUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
